### ISSUE TITLE
Unable to run deej-ai -- ubuntuish system

### ISSUE THREAD

**Issue by iconoclasthero** [teticio/Deej-AI#120]
```
$ python3 MP3ToVec.py Pickles mp3tovec --scan /library/music
2024-10-05 16:46:04.914706: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-05 16:46:04.918039: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-10-05 16:46:04.928888: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-05 16:46:04.945837: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-05 16:46:04.951047: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-05 16:46:05.975592: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Creating Track2Vec matrices
Traceback (most recent call last):
  File "/home/user/bin/gits/Deej-AI/MP3ToVec.py", line 50, in <module>
    tf.compat.v1.keras.losses.cosine_proximity
AttributeError: module 'keras._tf_keras.keras.losses' has no attribute 'cosine_proximity'
```

I downgraded keras to 2.11.0 which was what was listed in the requirements*txt files and then tensorflow wouldn't work.  pip has no install candidate for tensorflow 2.11.0.

Does this still work on a 24.04 or 24.10 ubuntu-based system?  I'm running Rhino 2024.2 which is using oracular's repos for now.  

I created a venv for the whole thing `~/.local/share/pipx/venvs/deejai`, activated, and used pip to install requirements.txt...

```
pwd: ~/bin/gits/Deej-AI $ pip install --requirement requirements.txt
Ignoring tensorflow-macos: markers 'sys_platform == "darwin"' don't match your environment
Ignoring tensorflow-metal: markers 'sys_platform == "darwin"' don't match your environment
Requirement already satisfied: dash in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (0.42.0)
Requirement already satisfied: tqdm in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from -r requirements.txt (line 2)) (4.66.5)
Requirement already satisfied: mutagen in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from -r requirements.txt (line 3)) (1.47.0)
Requirement already satisfied: Flask~=1.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from -r requirements.txt (line 4)) (1.1.4)
Requirement already satisfied: spotipy in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from -r requirements.txt (line 5)) (2.24.0)
Requirement already satisfied: librosa in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from -r requirements.txt (line 6)) (0.10.2.post1)
Requirement already satisfied: dash_core_components==0.47.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from -r requirements.txt (line 7)) (0.47.0)
Requirement already satisfied: dash_html_components==0.16.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from -r requirements.txt (line 8)) (0.16.0)
Requirement already satisfied: dash_daq==0.1.4 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from -r requirements.txt (line 9)) (0.1.4)
Requirement already satisfied: pandas in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from -r requirements.txt (line 11)) (2.2.3)
Requirement already satisfied: numpy in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from -r requirements.txt (line 12)) (1.26.4)
Requirement already satisfied: Pillow in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from -r requirements.txt (line 13)) (10.4.0)
Requirement already satisfied: tensorflow in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from -r requirements.txt (line 14)) (2.17.0)
Requirement already satisfied: numba in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from -r requirements.txt (line 17)) (0.60.0)
Requirement already satisfied: markupsafe==2.0.1 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from -r requirements.txt (line 18)) (2.0.1)
Requirement already satisfied: flask-compress in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from dash->-r requirements.txt (line 1)) (1.15)
Requirement already satisfied: plotly in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from dash->-r requirements.txt (line 1)) (5.24.1)
Requirement already satisfied: dash-renderer==0.23.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from dash->-r requirements.txt (line 1)) (0.23.0)
Requirement already satisfied: dash-table==3.6.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from dash->-r requirements.txt (line 1)) (3.6.0)
Requirement already satisfied: Werkzeug<2.0,>=0.15 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from Flask~=1.0->-r requirements.txt (line 4)) (1.0.1)
Requirement already satisfied: Jinja2<3.0,>=2.10.1 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from Flask~=1.0->-r requirements.txt (line 4)) (2.11.3)
Requirement already satisfied: itsdangerous<2.0,>=0.24 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from Flask~=1.0->-r requirements.txt (line 4)) (1.1.0)
Requirement already satisfied: click<8.0,>=5.1 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from Flask~=1.0->-r requirements.txt (line 4)) (7.1.2)
Requirement already satisfied: redis>=3.5.3 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from spotipy->-r requirements.txt (line 5)) (5.1.1)
Requirement already satisfied: requests>=2.25.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from spotipy->-r requirements.txt (line 5)) (2.32.3)
Requirement already satisfied: urllib3>=1.26.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from spotipy->-r requirements.txt (line 5)) (2.2.3)
Requirement already satisfied: audioread>=2.1.9 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from librosa->-r requirements.txt (line 6)) (3.0.1)
Requirement already satisfied: scipy>=1.2.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from librosa->-r requirements.txt (line 6)) (1.14.1)
Requirement already satisfied: scikit-learn>=0.20.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from librosa->-r requirements.txt (line 6)) (1.5.2)
Requirement already satisfied: joblib>=0.14 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from librosa->-r requirements.txt (line 6)) (1.4.2)
Requirement already satisfied: decorator>=4.3.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from librosa->-r requirements.txt (line 6)) (5.1.1)
Requirement already satisfied: soundfile>=0.12.1 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from librosa->-r requirements.txt (line 6)) (0.12.1)
Requirement already satisfied: pooch>=1.1 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from librosa->-r requirements.txt (line 6)) (1.8.2)
Requirement already satisfied: soxr>=0.3.2 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from librosa->-r requirements.txt (line 6)) (0.5.0.post1)
Requirement already satisfied: typing-extensions>=4.1.1 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from librosa->-r requirements.txt (line 6)) (4.12.2)
Requirement already satisfied: lazy-loader>=0.1 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from librosa->-r requirements.txt (line 6)) (0.4)
Requirement already satisfied: msgpack>=1.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from librosa->-r requirements.txt (line 6)) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from pandas->-r requirements.txt (line 11)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from pandas->-r requirements.txt (line 11)) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from pandas->-r requirements.txt (line 11)) (2024.2)
Requirement already satisfied: absl-py>=1.0.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 14)) (2.1.0)
Requirement already satisfied: astunparse>=1.6.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 14)) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 14)) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 14)) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 14)) (0.2.0)
Requirement already satisfied: h5py>=3.10.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 14)) (3.12.1)
Requirement already satisfied: libclang>=13.0.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 14)) (18.1.1)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.3.1 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 14)) (0.4.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 14)) (3.4.0)
Requirement already satisfied: packaging in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 14)) (24.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 14)) (4.25.5)
Requirement already satisfied: setuptools in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 14)) (75.1.0)
Requirement already satisfied: six>=1.12.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 14)) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 14)) (2.4.0)
Requirement already satisfied: wrapt>=1.11.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 14)) (1.16.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 14)) (1.66.2)
Requirement already satisfied: tensorboard<2.18,>=2.17 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 14)) (2.17.1)
Requirement already satisfied: keras>=3.2.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from tensorflow->-r requirements.txt (line 14)) (3.6.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from numba->-r requirements.txt (line 17)) (0.43.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from astunparse>=1.6.0->tensorflow->-r requirements.txt (line 14)) (0.44.0)
Requirement already satisfied: rich in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from keras>=3.2.0->tensorflow->-r requirements.txt (line 14)) (13.9.2)
Requirement already satisfied: namex in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from keras>=3.2.0->tensorflow->-r requirements.txt (line 14)) (0.0.8)
Requirement already satisfied: optree in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from keras>=3.2.0->tensorflow->-r requirements.txt (line 14)) (0.13.0)
Requirement already satisfied: platformdirs>=2.5.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from pooch>=1.1->librosa->-r requirements.txt (line 6)) (4.3.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from requests>=2.25.0->spotipy->-r requirements.txt (line 5)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from requests>=2.25.0->spotipy->-r requirements.txt (line 5)) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from requests>=2.25.0->spotipy->-r requirements.txt (line 5)) (2024.8.30)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from scikit-learn>=0.20.0->librosa->-r requirements.txt (line 6)) (3.5.0)
Requirement already satisfied: cffi>=1.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from soundfile>=0.12.1->librosa->-r requirements.txt (line 6)) (1.17.1)
Requirement already satisfied: markdown>=2.6.8 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from tensorboard<2.18,>=2.17->tensorflow->-r requirements.txt (line 14)) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from tensorboard<2.18,>=2.17->tensorflow->-r requirements.txt (line 14)) (0.7.2)
Requirement already satisfied: brotli in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from flask-compress->dash->-r requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: zstandard in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from flask-compress->dash->-r requirements.txt (line 1)) (0.23.0)
Requirement already satisfied: tenacity>=6.2.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from plotly->dash->-r requirements.txt (line 1)) (9.0.0)
Requirement already satisfied: pycparser in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from cffi>=1.0->soundfile>=0.12.1->librosa->-r requirements.txt (line 6)) (2.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from rich->keras>=3.2.0->tensorflow->-r requirements.txt (line 14)) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from rich->keras>=3.2.0->tensorflow->-r requirements.txt (line 14)) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /home/bvargo/.local/share/pipx/venvs/deejai/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->tensorflow->-r requirements.txt (line 14)) (0.1.2)
```

**Comment by teticio** [comment]
What version of Python are you using? It needs Python 3.8.

**Comment by teticio** [comment]
I will put something in the documentation or add a cosine proximity function for a newer version of Keras.

**Comment by teticio** [comment]
Added comment to use Python 3.10.
